// The PCIe end of the harness for UltraScale devices (the PCIE3 block,
// `pcie3_ultrascale`), wrapped so the rest of it does not have to look.
//
// **The same module as the UltraScale+ `hns_pcie_wrap.v`**, with the same
// ports, so the generated top does not change. The generator writes one of the
// two, by device family. The differences are in the hard block's ports; they
// were taken from the IP generated by Vivado 2021.2 for the KCU105
// (xcku040-ffva1156-2-e, gen3 x8, 256-bit, 250 MHz).
//
// **Written here, not borrowed.** The pieces inside are borrowed (see
// ../README.md); this file only puts them together and hides a hard block with
// 121 ports behind an interface with four wires and an AXI4-Lite port.
//
//     pcie pins --> pcie3_ultrascale --> pcie_us_axil_master --> axil_cdc --> out
//                          CQ/CC            (user_clk)          (harness clk)
//
// **All four streams are wired.** CQ/CC carry what the host does to our BAR,
// which is the window. RQ/RC are the half where the card issues: RQ carries
// both the memory writes `hns::dma_wr` makes and the memory reads `hns::dma_rd`
// makes, and RC brings the completions for the latter back.
//
// **The clock crossing is a handshake, not a queue.** One transaction is in
// flight at a time and each costs a round trip of flag synchronisers. That is
// far cheaper than the JTAG window it replaces, and buying depth means
// replacing `axil_cdc` with something that has a FIFO.
//
// The tie-offs follow the UltraScale+ wrapper, which runs on a board. Where
// the PCIE3 block differs, a comment says how.

`timescale 1ns / 1ps

// **An undeclared net is an error here, not a one-bit wire.** Without this,
// naming a net in a port connection before declaring it silently makes it one
// bit wide; a three-bit config value then reads back truncated and nothing
// says so louder than a warning. Cost us one synthesis run (2026-09-13).
`default_nettype none

module hns_pcie_wrap #(
    // The window's clock. The AXI-Lite side of the crossing runs here.
    parameter AXIL_ADDR_WIDTH = 32,
    // The BAR aperture, in address bits: 12 for a 4 KB BAR. The completer
    // takes the address straight out of the request, so it arrives with the
    // BAR base still on it (0x7a000000+off, wherever the BIOS put the BAR).
    // Handing the master only this many bits is what makes it BAR-relative --
    // the window range-checks the address, so an absolute one is rejected and
    // every access answers SLVERR.
    parameter BAR_ADDR_WIDTH = 12,
    // **The subsystem vendor ID is a port on this block**, not an IP setting
    // (`cfg_subsys_vend_id` goes straight to the block's CFGSUBSYSVENDID).
    // Left at zero, the device would report subsystem vendor 0.
    parameter [15:0] SUBSYSTEM_VENDOR_ID = 16'h10ee
) (
    // --- board ---
    input  wire        i_pcie_refclk_p,
    input  wire        i_pcie_refclk_n,
    input  wire        i_pcie_reset_n,
    input  wire [7:0]  i_pcie_rx_p,
    input  wire [7:0]  i_pcie_rx_n,
    output wire [7:0]  o_pcie_tx_p,
    output wire [7:0]  o_pcie_tx_n,

    // --- the harness side ---
    input  wire        i_clk,          // the window's clock
    input  wire        i_rst_n,        // active low, the window's reset
    output wire        o_link_up,      // synchronised into i_clk

    // --- requester (RQ/RC), in the block's own clock ---
    //
    // **These are the only things here that are not in i_clk.** Everything else
    // the wrapper hands out has already been brought across; these streams have
    // not, because the crossing belongs in a reviewed part rather than in
    // hand-written Verilog here. `hns::rq_cdc` puts a std async FIFO on each.
    output wire        o_user_clk,
    output wire        o_user_reset,   // active high, synchronised into o_user_clk
    input  wire [255:0] i_rq_tdata,
    input  wire [7:0]   i_rq_tkeep,
    input  wire         i_rq_tlast,
    input  wire [59:0]  i_rq_tuser,
    input  wire         i_rq_tvalid,
    output wire         o_rq_tready,

    // Completions coming back for the reads the card issued. **Wider tuser
    // than RQ** (75 against 60): it carries the completion status, the byte
    // enables and the error bits, which `pcie_us_axi_dma_rd` reads.
    output wire [255:0] o_rc_tdata,
    output wire [7:0]   o_rc_tkeep,
    output wire         o_rc_tlast,
    output wire [74:0]  o_rc_tuser,
    output wire         o_rc_tvalid,
    input  wire         i_rc_tready,

    // What the link negotiated, synchronised into i_clk. 3'b000 is 128 bytes,
    // each step doubling. The requester splits its payloads by this; it is the
    // block that knows it, so the harness does not guess.
    output wire [2:0]  o_max_payload,

    // The read counterpart: how much the host allows one read request to ask
    // for. Same encoding, same reason for coming from here rather than being
    // guessed -- `hns::dma_rd` splits its requests by it.
    output wire [2:0]  o_max_read_req,

    // Local errors the block reported, as a saturating count **in gray code, in
    // o_user_clk**. **On this block it counts every local error**, not only
    // dropped requester TLPs: `cfg_local_error` is one bit and carries no error
    // code (the UltraScale+ block has one). It counts more than the name says,
    // so it never hides a drop. Gray so that the harness can bring it over with
    // a plain synchroniser.
    output wire [15:0] o_rq_drops_gray,

    output wire [AXIL_ADDR_WIDTH-1:0] o_awaddr,
    output wire                       o_awvalid,
    input  wire                       i_awready,
    output wire [31:0]                o_wdata,
    output wire [3:0]                 o_wstrb,
    output wire                       o_wvalid,
    input  wire                       i_wready,
    input  wire [1:0]                 i_bresp,
    input  wire                       i_bvalid,
    output wire                       o_bready,
    output wire [AXIL_ADDR_WIDTH-1:0] o_araddr,
    output wire                       o_arvalid,
    input  wire                       i_arready,
    input  wire [31:0]                i_rdata,
    input  wire [1:0]                 i_rresp,
    input  wire                       i_rvalid,
    output wire                       o_rready
);

    // --- reference clock ---
    // ODIV2 feeds the IP's sys_clk; the GT clock goes to sys_clk_gt. Both come
    // from one buffer: the transceivers and the block must see the same source.
    wire pcie_sys_clk;
    wire pcie_sys_clk_gt;

    IBUFDS_GTE3 #(.REFCLK_HROW_CK_SEL(2'b00)) ibufds_gte3_pcie_inst (
        .I(i_pcie_refclk_p), .IB(i_pcie_refclk_n), .CEB(1'b0),
        .O(pcie_sys_clk_gt), .ODIV2(pcie_sys_clk)
    );

    wire pcie_user_clk;
    wire pcie_user_reset_int;

    // The IP's user_reset is asynchronous to nothing in particular; it is
    // resynchronised into user_clk before anything uses it.
    (* shreg_extract = "no" *) reg user_reset_reg_1 = 1'b1;
    (* shreg_extract = "no" *) reg user_reset_reg_2 = 1'b1;
    always @(posedge pcie_user_clk) begin
        user_reset_reg_1 <= pcie_user_reset_int;
        user_reset_reg_2 <= user_reset_reg_1;
    end
    wire pcie_user_reset = user_reset_reg_2;

    // --- the streams we use ---
    wire [255:0] axis_cq_tdata;
    wire [7:0]   axis_cq_tkeep;
    wire         axis_cq_tlast;
    wire         axis_cq_tready;
    // **85, not 88.** The UltraScale+ block carries three more bits. The bridge
    // accepts either width.
    wire [84:0]  axis_cq_tuser;
    wire         axis_cq_tvalid;

    wire [255:0] axis_cc_tdata;
    wire [7:0]   axis_cc_tkeep;
    wire         axis_cc_tlast;
    // **Four bits, one meaning.** The block replicates completion-ready across
    // the straddle segments; straddling is off, so bit 0 is the answer.
    wire [3:0]   axis_cc_tready;
    wire [32:0]  axis_cc_tuser;
    wire         axis_cc_tvalid;

    wire        user_lnk_up;
    // **Four bits, one meaning** -- same as CC above. The block replicates
    // ready across the straddle segments; straddling is off, so bit 0 is the
    // answer. Declaring one bit against a four-bit port is the width mismatch
    // this file already warns about twice.
    wire [3:0]  rq_tready;

    // The block's local error flag. One bit, no code (o_rq_drops_gray).
    wire        local_error;

    assign o_rq_tready  = rq_tready[0];
    assign o_user_clk   = pcie_user_clk;
    assign o_user_reset = pcie_user_reset;

    // Flow-control readback the block asks for even when unused.
    wire [7:0]  cfg_fc_ph, cfg_fc_nph, cfg_fc_cplh;
    wire [11:0] cfg_fc_pd, cfg_fc_npd, cfg_fc_cpld;

    // **Declared before they are used, not after.** Verilog gives an
    // undeclared net in a port connection an implicit *one-bit* wire, so
    // declaring these below the instance below made them 1 bit wide at the
    // point that mattered: payload codes 0 and 1 survived and 2 (512 bytes)
    // read back as 0. Vivado only said "already implicitly declared earlier".
    wire [2:0] cfg_max_payload;
    wire [2:0] cfg_max_read_req;

    pcie3_ultrascale_0 pcie3_ultrascale_inst (
        .pci_exp_txn(o_pcie_tx_n),
        .pci_exp_txp(o_pcie_tx_p),
        .pci_exp_rxn(i_pcie_rx_n),
        .pci_exp_rxp(i_pcie_rx_p),
        .user_clk(pcie_user_clk),
        .user_reset(pcie_user_reset_int),
        .user_lnk_up(user_lnk_up),

        // Requester (RQ): driven from outside, in this clock. **tuser is 60
        // bits on this block**, the width the requester drives, so there is no
        // padding.
        .s_axis_rq_tdata(i_rq_tdata),
        .s_axis_rq_tkeep(i_rq_tkeep),
        .s_axis_rq_tlast(i_rq_tlast),
        .s_axis_rq_tready(rq_tready),
        .s_axis_rq_tuser(i_rq_tuser),
        .s_axis_rq_tvalid(i_rq_tvalid),
        .m_axis_rc_tdata(o_rc_tdata),
        .m_axis_rc_tkeep(o_rc_tkeep),
        .m_axis_rc_tlast(o_rc_tlast),
        // **A completion that is never taken wedges the block.** Whatever sits
        // downstream has to keep draining.
        .m_axis_rc_tready(i_rc_tready),
        .m_axis_rc_tuser(o_rc_tuser),
        .m_axis_rc_tvalid(o_rc_tvalid),

        // Completer: this is the window.
        .m_axis_cq_tdata(axis_cq_tdata),
        .m_axis_cq_tkeep(axis_cq_tkeep),
        .m_axis_cq_tlast(axis_cq_tlast),
        .m_axis_cq_tready(axis_cq_tready),
        .m_axis_cq_tuser(axis_cq_tuser),
        .m_axis_cq_tvalid(axis_cq_tvalid),
        .s_axis_cc_tdata(axis_cc_tdata),
        .s_axis_cc_tkeep(axis_cc_tkeep),
        .s_axis_cc_tlast(axis_cc_tlast),
        .s_axis_cc_tready(axis_cc_tready),
        .s_axis_cc_tuser(axis_cc_tuser),
        .s_axis_cc_tvalid(axis_cc_tvalid),

        .pcie_rq_seq_num(), .pcie_rq_seq_num_vld(),
        .pcie_rq_tag(), .pcie_rq_tag_av(), .pcie_rq_tag_vld(),
        .pcie_tfc_nph_av(), .pcie_tfc_npd_av(),
        // **Non-posted requests are allowed.** Reads of our BAR are
        // non-posted; holding this low stops the host reading anything.
        .pcie_cq_np_req(1'b1),
        .pcie_cq_np_req_count(),

        .cfg_phy_link_down(), .cfg_phy_link_status(),
        .cfg_negotiated_width(), .cfg_current_speed(),
        .cfg_max_payload(cfg_max_payload), .cfg_max_read_req(cfg_max_read_req),
        .cfg_function_status(), .cfg_function_power_state(),
        .cfg_vf_status(), .cfg_vf_power_state(), .cfg_link_power_state(),

        // Configuration-space management: unused.
        .cfg_mgmt_addr(19'd0),
        .cfg_mgmt_write(1'b0),
        .cfg_mgmt_write_data(32'd0),
        .cfg_mgmt_byte_enable(4'd0),
        .cfg_mgmt_read(1'b0),
        .cfg_mgmt_read_data(),
        .cfg_mgmt_read_write_done(),
        .cfg_mgmt_type1_cfg_reg_access(1'b0),

        .cfg_err_cor_out(), .cfg_err_nonfatal_out(), .cfg_err_fatal_out(),
        .cfg_local_error(local_error), .cfg_ltr_enable(),
        .cfg_ltssm_state(), .cfg_rcb_status(), .cfg_dpa_substate_change(),
        .cfg_obff_enable(), .cfg_pl_status_change(),
        .cfg_tph_requester_enable(), .cfg_tph_st_mode(),
        .cfg_vf_tph_requester_enable(), .cfg_vf_tph_st_mode(),
        .cfg_msg_received(), .cfg_msg_received_data(), .cfg_msg_received_type(),
        .cfg_msg_transmit(1'b0), .cfg_msg_transmit_type(3'd0),
        .cfg_msg_transmit_data(32'd0), .cfg_msg_transmit_done(),

        .cfg_fc_ph(cfg_fc_ph), .cfg_fc_pd(cfg_fc_pd),
        .cfg_fc_nph(cfg_fc_nph), .cfg_fc_npd(cfg_fc_npd),
        .cfg_fc_cplh(cfg_fc_cplh), .cfg_fc_cpld(cfg_fc_cpld),
        .cfg_fc_sel(3'd0),

        // Per-function status readback: unused.
        .cfg_per_func_status_control(3'd0),
        .cfg_per_func_status_data(),
        .cfg_per_function_number(4'd0),
        .cfg_per_function_output_request(1'b0),
        .cfg_per_function_update_done(),

        .cfg_dsn(64'd0),
        // **Acknowledge power-state changes.** Never answering can stall the
        // link when the host tries to move us.
        .cfg_power_state_change_ack(1'b1),
        .cfg_power_state_change_interrupt(),
        .cfg_err_cor_in(1'b0),
        .cfg_err_uncor_in(1'b0),
        .cfg_flr_in_process(), .cfg_flr_done(4'd0),
        .cfg_vf_flr_in_process(), .cfg_vf_flr_done(8'd0),
        // Without this the link never trains.
        .cfg_link_training_enable(1'b1),
        .cfg_interrupt_int(4'd0),
        .cfg_interrupt_pending(4'd0),
        .cfg_interrupt_sent(),
        .cfg_hot_reset_out(),
        // Without this the device answers nothing on its BAR.
        .cfg_config_space_enable(1'b1),
        .cfg_req_pm_transition_l23_ready(1'b0),
        .cfg_hot_reset_in(1'b0),
        .cfg_ds_port_number(8'd0),
        .cfg_ds_bus_number(8'd0),
        .cfg_ds_device_number(5'd0),
        .cfg_ds_function_number(3'd0),
        .cfg_subsys_vend_id(SUBSYSTEM_VENDOR_ID),

        .sys_clk(pcie_sys_clk),
        .sys_clk_gt(pcie_sys_clk_gt),
        .sys_reset(i_pcie_reset_n),
        // The MCAP reset of the second block, which is not used. Tied to 0,
        // the IP's own default and what its example design leaves it at.
        // **Not to PERST#**: the placer then tries to put the PERST# pin in the
        // second block's shape as well, and fails (Shape Builder 18-119).
        .pcie_perstn1_in(1'b0),
        .pcie_perstn0_out(),
        .pcie_perstn1_out(),
        .int_qpll1lock_out(),
        .int_qpll1outrefclk_out(),
        .int_qpll1outclk_out(),
        .phy_rdy_out()
    );

    // --- CQ/CC -> AXI-Lite, in the PCIe user clock domain ---
    wire [BAR_ADDR_WIDTH-1:0]  u_awaddr, u_araddr;   // BAR-relative
    wire [BAR_ADDR_WIDTH-1:0]  c_awaddr, c_araddr;   // the same, once across
    wire                       u_awvalid, u_awready, u_wvalid, u_wready;
    wire [31:0]                u_wdata, u_rdata;
    wire [3:0]                 u_wstrb;
    wire [1:0]                 u_bresp, u_rresp;
    wire                       u_bvalid, u_bready, u_arvalid, u_arready;
    wire                       u_rvalid, u_rready;

    pcie_us_axil_master #(
        .AXIS_PCIE_DATA_WIDTH(256),
        .AXIS_PCIE_CQ_USER_WIDTH(85),
        .AXIS_PCIE_CC_USER_WIDTH(33),
        .AXI_DATA_WIDTH(32),
        .AXI_ADDR_WIDTH(BAR_ADDR_WIDTH),
        .ENABLE_PARITY(0)
    ) axil_master_inst (
        .clk(pcie_user_clk),
        .rst(pcie_user_reset),
        .s_axis_cq_tdata(axis_cq_tdata),
        .s_axis_cq_tkeep(axis_cq_tkeep),
        .s_axis_cq_tvalid(axis_cq_tvalid),
        .s_axis_cq_tready(axis_cq_tready),
        .s_axis_cq_tlast(axis_cq_tlast),
        .s_axis_cq_tuser(axis_cq_tuser),
        .m_axis_cc_tdata(axis_cc_tdata),
        .m_axis_cc_tkeep(axis_cc_tkeep),
        .m_axis_cc_tvalid(axis_cc_tvalid),
        .m_axis_cc_tready(axis_cc_tready[0]),
        .m_axis_cc_tlast(axis_cc_tlast),
        .m_axis_cc_tuser(axis_cc_tuser),
        .m_axil_awaddr(u_awaddr),
        .m_axil_awprot(),
        .m_axil_awvalid(u_awvalid),
        .m_axil_awready(u_awready),
        .m_axil_wdata(u_wdata),
        .m_axil_wstrb(u_wstrb),
        .m_axil_wvalid(u_wvalid),
        .m_axil_wready(u_wready),
        .m_axil_bresp(u_bresp),
        .m_axil_bvalid(u_bvalid),
        .m_axil_bready(u_bready),
        .m_axil_araddr(u_araddr),
        .m_axil_arprot(),
        .m_axil_arvalid(u_arvalid),
        .m_axil_arready(u_arready),
        .m_axil_rdata(u_rdata),
        .m_axil_rresp(u_rresp),
        .m_axil_rvalid(u_rvalid),
        .m_axil_rready(u_rready),
        .completer_id(16'd0),
        .completer_id_enable(1'b0),
        .status_error_cor(),
        .status_error_uncor()
    );

    // --- across to the window's clock ---
    axil_cdc #(
        .DATA_WIDTH(32),
        .ADDR_WIDTH(BAR_ADDR_WIDTH)
    ) axil_cdc_inst (
        .s_clk(pcie_user_clk),
        .s_rst(pcie_user_reset),
        .s_axil_awaddr(u_awaddr),
        .s_axil_awprot(3'd0),
        .s_axil_awvalid(u_awvalid),
        .s_axil_awready(u_awready),
        .s_axil_wdata(u_wdata),
        .s_axil_wstrb(u_wstrb),
        .s_axil_wvalid(u_wvalid),
        .s_axil_wready(u_wready),
        .s_axil_bresp(u_bresp),
        .s_axil_bvalid(u_bvalid),
        .s_axil_bready(u_bready),
        .s_axil_araddr(u_araddr),
        .s_axil_arprot(3'd0),
        .s_axil_arvalid(u_arvalid),
        .s_axil_arready(u_arready),
        .s_axil_rdata(u_rdata),
        .s_axil_rresp(u_rresp),
        .s_axil_rvalid(u_rvalid),
        .s_axil_rready(u_rready),

        .m_clk(i_clk),
        .m_rst(~i_rst_n),
        .m_axil_awaddr(c_awaddr),
        .m_axil_awprot(),
        .m_axil_awvalid(o_awvalid),
        .m_axil_awready(i_awready),
        .m_axil_wdata(o_wdata),
        .m_axil_wstrb(o_wstrb),
        .m_axil_wvalid(o_wvalid),
        .m_axil_wready(i_wready),
        .m_axil_bresp(i_bresp),
        .m_axil_bvalid(i_bvalid),
        .m_axil_bready(o_bready),
        .m_axil_araddr(c_araddr),
        .m_axil_arprot(),
        .m_axil_arvalid(o_arvalid),
        .m_axil_arready(i_arready),
        .m_axil_rdata(i_rdata),
        .m_axil_rresp(i_rresp),
        .m_axil_rvalid(i_rvalid),
        .m_axil_rready(o_rready)
    );

    // Back to the window's bus width. The high bits are zero -- the window
    // starts where the BAR starts, so an offset is the whole address.
    assign o_awaddr = {{(AXIL_ADDR_WIDTH - BAR_ADDR_WIDTH){1'b0}}, c_awaddr};
    assign o_araddr = {{(AXIL_ADDR_WIDTH - BAR_ADDR_WIDTH){1'b0}}, c_araddr};

    // Max payload size, brought over the same way. Two flops per bit: the host
    // sets it once at enumeration, and the requester samples it only while it is
    // idle, so no descriptor sees it change (hns::dma_wr).
    (* shreg_extract = "no" *) reg [2:0] mps_reg_1 = 3'b000;
    (* shreg_extract = "no" *) reg [2:0] mps_reg_2 = 3'b000;
    always @(posedge i_clk) begin
        mps_reg_1 <= cfg_max_payload;
        mps_reg_2 <= mps_reg_1;
    end
    assign o_max_payload = mps_reg_2;

    // Max read request size, the same way and for the same reason.
    (* shreg_extract = "no" *) reg [2:0] mrrs_reg_1 = 3'b000;
    (* shreg_extract = "no" *) reg [2:0] mrrs_reg_2 = 3'b000;
    always @(posedge i_clk) begin
        mrrs_reg_1 <= cfg_max_read_req;
        mrrs_reg_2 <= mrrs_reg_1;
    end
    assign o_max_read_req = mrrs_reg_2;

    // Link state, brought over for the host to read. Two flops: it is a hint,
    // not a handshake.
    (* shreg_extract = "no" *) reg lnk_up_reg_1 = 1'b0;
    (* shreg_extract = "no" *) reg lnk_up_reg_2 = 1'b0;
    always @(posedge i_clk) begin
        lnk_up_reg_1 <= user_lnk_up;
        lnk_up_reg_2 <= lnk_up_reg_1;
    end
    assign o_link_up = lnk_up_reg_2;

    // Local errors, counted where the block reports them. **Not reset** -- a
    // link reset is exactly when the count is worth keeping. Saturates, so a
    // count never wraps back to looking clean. Counted on the rising edge, so
    // an error that holds the flag for several cycles counts once.
    reg        local_error_q = 1'b0;
    reg [15:0] rq_drops = 16'd0;
    reg [15:0] rq_drops_gray = 16'd0;
    wire [15:0] rq_drops_next = rq_drops + 16'd1;
    always @(posedge pcie_user_clk) begin
        local_error_q <= local_error;
        if (local_error && !local_error_q && rq_drops != 16'hffff) begin
            rq_drops      <= rq_drops_next;
            rq_drops_gray <= rq_drops_next ^ (rq_drops_next >> 1);
        end
    end
    assign o_rq_drops_gray = rq_drops_gray;

endmodule

`default_nettype wire
